spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:sqlmapper/*Mapper.xml
  type-aliases-package: com.oranfish.sushidao

server:
  servlet:
    context-path: /sushi